# Chapter 4 - Data Types and Structures

<br></br>
## 1 기본자료형
정수

### 01 숫자
Integer/ float

In [1]:
a = 10
a.bit_length() # 정수의 bit 수를 출력

4

### 02 문자
String

In [2]:
t = 'this is a Strong object.'

In [3]:
# 문장의 첫단어를 대문자로 변환한다
t.capitalize()

'This is a strong object.'

In [4]:
# Split by Word 
t.split()

['this', 'is', 'a', 'Strong', 'object.']

In [5]:
'https://www.python.org'.split('://')

['https', 'www.python.org']

In [6]:
# 특정 단어가 나타나는 Index값
t.find('object')

17

In [7]:
t.find('python') # 내용이 없으면 '-1'을 출력한다

-1

### 03 문자
by Regular Express

In [8]:
import re
series = """'01/18/2014 13:00:00', 100, '1st';
'01/18/2014 13:30:00', 110, '2nd';
'01/18/2014 14:00:00', 120, '3rd'"""

In [9]:
# datetime
dt = re.compile("'[0-9/:\s]+'")    # 정규식 모델
result = dt.findall(series)        # 정규식에 해당 객체들 list로 추출
result

["'01/18/2014 13:00:00'", "'01/18/2014 13:30:00'", "'01/18/2014 14:00:00'"]

In [10]:
# %m %d %Y 의 포맷이 일치해야 정상적 추출가능
from datetime import datetime
pydt = datetime.strptime(result[0].replace("'", ""),
                         '%m/%d/%Y %H:%M:%S')
pydt

datetime.datetime(2014, 1, 18, 13, 0)

In [11]:
print(pydt)

2014-01-18 13:00:00


In [12]:
print(type(pydt))

<class 'datetime.datetime'>


<br></br>
## 2 기본 자료구조
Data Structure

### 01 튜플
tuple 수정이 어려워서 유연성이 떨어진다

In [13]:
t = 1, 2.5, 'data'
tuple(t)

(1, 2.5, 'data')

In [14]:
t[2]

'data'

### 02 [ list ]
유연해서 활용에 용이하다

In [15]:
l = [1, 2.5, 'data']

In [16]:
l.append([4,3]); l

[1, 2.5, 'data', [4, 3]]

In [17]:
l = l + [1,2,3]; l

[1, 2.5, 'data', [4, 3], 1, 2, 3]

In [18]:
l.insert(1,'insert'); l

[1, 'insert', 2.5, 'data', [4, 3], 1, 2, 3]

In [19]:
# 해당 객체를 삭제한다
l.remove('data'); l

[1, 'insert', 2.5, [4, 3], 1, 2, 3]

In [20]:
# 해당 index의 자료를 출력하고, 자료에서 삭제한다
l.pop(3)

[4, 3]

In [21]:
l

[1, 'insert', 2.5, 1, 2, 3]

<br></br>
## 3 제어구조
유연해서 활용에 용이하다

### 01 기본구조형
for/ if

In [22]:
for element in l[2:5]:
    print(element * 2)

5.0
2
4


In [23]:
r = range(0,8,1); r

range(0, 8)

In [24]:
for i in range(1, 10):
    if i % 2 == 0:  # % is for modulo
        print("%d is even" % i)
    elif i % 3 == 0:
        print("%d is multiple of 3" % i)
    else:
        print("%d is odd" % i)

1 is odd
2 is even
3 is multiple of 3
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is multiple of 3


In [25]:
total = 0
while total < 100:
    total += 1
print(total)

100


In [26]:
# 리스트 조건제시법
m = [i ** 2 for i in range(5)]
m

[0, 1, 4, 9, 16]

### 02 함수형 프로그래밍
filter, map, reduce : 이들은 [list] 객체에 적용한다

In [27]:
def f(x):
    return x ** 2
f(2)

4

In [28]:
def even(x):
    return x % 2 == 0
even(3)

False

In [29]:
# map() : 각 list 객체에 함수를 그대로 적용
list(map(even, range(10)))

[True, False, True, False, True, False, True, False, True, False]

In [30]:
list(map(lambda x: x ** 2, range(10)))  # True 결과값에 적용한 함수를 lambda로 적용

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [31]:
# filter() : 각 list 객체에 함수적용 후 True 값만 List로 추출 (추가 연산을 한다)
list(filter(even, range(15)))

[0, 2, 4, 6, 8, 10, 12, 14]

<br></br>
## 4 Numpy
ndarray : List 보다 다양하고, 복잡한 연산을 쉽게 수행가능

## 01  array
1차원 자료형

In [32]:
import numpy as np
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
type(a)

numpy.ndarray

In [33]:
# Slicing 에 용이하다 : list와 동일
a[:2]  

array([ 0. ,  0.5])

In [34]:
print(a.sum())     # 객체의 총합
print(a.std())     # 객체의 표준편차
print(a.cumsum())  # 객체의 누적합
print(a * 2)
np.sqrt(a)         # Sequare : 제곱근 (벡터화된 수학연산도 가능)

5.0
0.707106781187
[ 0.   0.5  1.5  3.   5. ]
[ 0.  1.  2.  3.  4.]


array([ 0.        ,  0.70710678,  1.        ,  1.22474487,  1.41421356])

## 02 array
2차원 자료형

In [35]:
b = np.array([a, a * 2])
print('b      :', b)
print('b[0]   :', b[0])      # 첫 행
print('b[0, 2]:',b[0, 2])   # 첫 행, 두번째 객체 
print('b.sum():',b.sum())

b      : [[ 0.   0.5  1.   1.5  2. ]
 [ 0.   1.   2.   3.   4. ]]
b[0]   : [ 0.   0.5  1.   1.5  2. ]
b[0, 2]: 1.0
b.sum(): 15.0


In [36]:
b.sum(axis=0)  # 0번 축의 합

array([ 0. ,  1.5,  3. ,  4.5,  6. ])

In [37]:
b.sum(axis=1)  # 1번 축의 합 (row/ column 의 구분이 아니다!!!!)

array([  5.,  10.])

## 03 ndarray
NOT-DEFINED-array : 특정한 원소값이 없이 생성을 시작한 객체

In [38]:
# also: np.ones()
c = np.zeros((2, 3, 4), dtype='i', order='C')  ; c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [39]:
# also: np.zeros_like()
d = np.ones_like(c, dtype='f16', order='C')  ; d

array([[[ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0]],

       [[ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0]]], dtype=float128)

In [40]:
import random
I = 5000 

In [41]:
%time mat = [[random.gauss(0, 1) for j in range(I)] for i in range(I)]
  # a nested list comprehension

CPU times: user 18.1 s, sys: 192 ms, total: 18.3 s
Wall time: 18.3 s


In [42]:
%time mat = np.random.standard_normal((I, I))

CPU times: user 1.26 s, sys: 44 ms, total: 1.31 s
Wall time: 1.31 s


In [43]:
%time mat.sum()

CPU times: user 16 ms, sys: 0 ns, total: 16 ms
Wall time: 14 ms


-2808.5899460646551

## 04 ndarray 의 구조화 배열 (Structured Arrays)
SQL의 Table 생성과 유사하게, 개별 field의 '이름', '추가정보'를 지정한다

In [44]:
# defined the DataType
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'), ('Height', 'f'), ('Children/Pets', 'i4', 2)])
s  = np.array([('Smith',          45,            1.83,            (0, 1)), 
               ('Jones',          53,            1.72,            (2, 2))], dtype=dt)
s

array([(b'Smith', 45,  1.83000004, [0, 1]),
       (b'Jones', 53,  1.72000003, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [45]:
# Name 필드의 데이터, S10 : string은 max 10개
s['Name']

array([b'Smith', b'Jones'],
      dtype='|S10')

In [46]:
s['Height'].mean()  # 해당 field의 값들을 연산

1.7750001

In [47]:
s[1]['Age']  # indexing

53

## 05 벡터객체의 연산
Matrix 전체를 한번에 연산한다

In [48]:
r = np.random.standard_normal((4, 3))
s = np.random.standard_normal((4, 3))
r + s

array([[-1.13776827,  1.27401041, -1.58982016],
       [ 0.7442754 , -0.01255866, -0.27315438],
       [ 2.28624228,  0.93576646,  2.33428212],
       [-1.23717658, -2.53751927, -1.18671525]])

In [49]:
2 * r + 3

array([[ 3.28869565,  6.27256441,  2.60094381],
       [ 6.60409418,  1.55335428,  0.23740177],
       [ 6.96960207,  2.70038897,  3.67552838],
       [ 1.9951252 ,  0.41156296, -0.7438124 ]])

In [50]:
# 차원은 달라도, 브로드캐스팅이 가능한 객체수인 경우 연산이 진행
s = np.random.standard_normal(3)
print(s)
r + s

[ 0.19113907  0.79207465 -0.1808665 ]


array([[ 0.33548689,  2.42835686, -0.38039459],
       [ 1.99318615,  0.06875179, -1.56216561],
       [ 2.1759401 ,  0.64226913,  0.15689769],
       [-0.31129834, -0.50214387, -2.0527727 ]])

In [51]:
# 객체수가 맞지 않으면 '브로드캐스팅'은 되지 않는다
# s = np.random.standard_normal(4)
# r + s

In [52]:
# numpy 내부의 shape() 함수
np.shape(r.T)

(3, 4)

In [53]:
def f(x):
    return 3 * x + 5

f(r)  # Matrix 객체에도 간단한 사칙연산이 적용

array([[  5.43304348,   9.90884661,   4.40141571],
       [ 10.40614127,   2.83003142,   0.85610266],
       [ 10.95440311,   4.55058345,   6.01329257],
       [  3.4926878 ,   1.11734445,  -0.61571861]])

<br></br>
## 5 메모리의 배열/ 배치
Memory Layout

In [54]:
x = np.random.standard_normal((5, 10000000))
y = 2 * x + 3  # linear equation y = a * x + b

# 객체 C 생성
C = np.array((x, y), order='C')
C[:2].round(2)

array([[[ 0.6 ,  0.83, -2.57, ...,  0.32,  1.39,  0.06],
        [ 0.31,  1.98,  0.1 , ..., -1.54,  0.59,  0.84],
        [ 1.05,  2.2 , -2.82, ..., -0.73,  0.5 ,  0.35],
        [ 0.52, -0.56,  0.63, ..., -1.09, -0.99, -0.88],
        [ 0.61, -1.17, -1.88, ...,  1.28,  0.22,  1.62]],

       [[ 4.2 ,  4.66, -2.15, ...,  3.63,  5.79,  3.12],
        [ 3.61,  6.96,  3.2 , ..., -0.09,  4.17,  4.68],
        [ 5.09,  7.39, -2.64, ...,  1.54,  4.  ,  3.69],
        [ 4.04,  1.87,  4.26, ...,  0.82,  1.02,  1.23],
        [ 4.23,  0.66, -0.76, ...,  5.55,  3.44,  6.24]]])

In [55]:
# 객체 F 생성
F = np.array((x, y), order='F')
x = 0.0; y = 0.0  # memory clean-up

In [56]:
%timeit C.sum()
%timeit F.sum()

10 loops, best of 3: 41.3 ms per loop
10 loops, best of 3: 41.3 ms per loop


In [57]:
# C 객체를 나누면, 개별객체 메모리 재배치로 오히려 느리다
%timeit C[0].sum(axis=0)
%timeit C[0].sum(axis=1)

10 loops, best of 3: 61.1 ms per loop
10 loops, best of 3: 20.7 ms per loop


In [58]:
%timeit F.sum(axis=0)
%timeit F.sum(axis=1)

1 loop, best of 3: 614 ms per loop
1 loop, best of 3: 1.62 s per loop


In [59]:
# 결론
# 파이썬의 기본 자료형을 공부했다
# 금융알고지름은 '배열의 형태로 주어지므로 
# array, ndarray 기타 특수 클래스를 활용하면 성능이 향상된다