# Chapter 4 - Data Types and Structures

<br></br>
## 1 기본자료형
정수

### 01 숫자
Integer/ float

In [1]:
a = 10
a.bit_length() # 정수의 bit 수를 출력

4

### 02 문자
String

In [2]:
t = 'this is a Strong object.'

In [3]:
# 문장의 첫단어를 대문자로 변환한다
t.capitalize()

'This is a strong object.'

In [4]:
# Split by Word 
t.split()

['this', 'is', 'a', 'Strong', 'object.']

In [5]:
'https://www.python.org'.split('://')

['https', 'www.python.org']

In [6]:
# 특정 단어가 나타나는 Index값
t.find('object')

17

In [7]:
t.find('python') # 내용이 없으면 '-1'을 출력한다

-1

### 03 문자
by Regular Express

In [8]:
import re
series = """'01/18/2014 13:00:00', 100, '1st';
'01/18/2014 13:30:00', 110, '2nd';
'01/18/2014 14:00:00', 120, '3rd'"""

In [9]:
# datetime
dt = re.compile("'[0-9/:\s]+'")    # 정규식 모델
result = dt.findall(series)        # 정규식에 해당 객체들 list로 추출
result

["'01/18/2014 13:00:00'", "'01/18/2014 13:30:00'", "'01/18/2014 14:00:00'"]

In [10]:
# %m %d %Y 의 포맷이 일치해야 정상적 추출가능
from datetime import datetime
pydt = datetime.strptime(result[0].replace("'", ""),
                         '%m/%d/%Y %H:%M:%S')
pydt

datetime.datetime(2014, 1, 18, 13, 0)

In [11]:
print(pydt)

2014-01-18 13:00:00


In [12]:
print(type(pydt))

<class 'datetime.datetime'>


<br></br>
## 2 기본 자료구조
Data Structure

### 01 튜플
tuple 수정이 어려워서 유연성이 떨어진다

In [13]:
t = 1, 2.5, 'data'
tuple(t)

(1, 2.5, 'data')

In [14]:
t[2]

'data'

### 02 [ list ]
유연해서 활용에 용이하다

In [15]:
l = [1, 2.5, 'data']

In [16]:
l.append([4,3]); l

[1, 2.5, 'data', [4, 3]]

In [17]:
l = l + [1,2,3]; l

[1, 2.5, 'data', [4, 3], 1, 2, 3]

In [18]:
l.insert(1,'insert'); l

[1, 'insert', 2.5, 'data', [4, 3], 1, 2, 3]

In [19]:
# 해당 객체를 삭제한다
l.remove('data'); l

[1, 'insert', 2.5, [4, 3], 1, 2, 3]

In [20]:
# 해당 index의 자료를 출력하고, 자료에서 삭제한다
l.pop(3)

[4, 3]

In [21]:
l

[1, 'insert', 2.5, 1, 2, 3]

<br></br>
## 3 제어구조
유연해서 활용에 용이하다

### 01 기본구조형
for/ if

In [22]:
for element in l[2:5]:
    print(element * 2)

5.0
2
4


In [23]:
r = range(0,8,1); r

range(0, 8)

In [24]:
for i in range(1, 10):
    if i % 2 == 0:  # % is for modulo
        print("%d is even" % i)
    elif i % 3 == 0:
        print("%d is multiple of 3" % i)
    else:
        print("%d is odd" % i)

1 is odd
2 is even
3 is multiple of 3
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is multiple of 3


In [25]:
total = 0
while total < 100:
    total += 1
print(total)

100


In [26]:
# 리스트 조건제시법
m = [i ** 2 for i in range(5)]
m

[0, 1, 4, 9, 16]

### 02 함수형 프로그래밍
filter, map, reduce : 이들은 [list] 객체에 적용한다

In [27]:
def f(x):
    return x ** 2
f(2)

4

In [28]:
def even(x):
    return x % 2 == 0
even(3)

False

In [29]:
# map() : 각 list 객체에 함수를 그대로 적용
list(map(even, range(10)))

[True, False, True, False, True, False, True, False, True, False]

In [30]:
list(map(lambda x: x ** 2, range(10)))  # True 결과값에 적용한 함수를 lambda로 적용

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [31]:
# filter() : 각 list 객체에 함수적용 후 True 값만 List로 추출 (추가 연산을 한다)
list(filter(even, range(15)))

[0, 2, 4, 6, 8, 10, 12, 14]

<br></br>
## 4 Numpy
ndarray : List 보다 다양하고, 복잡한 연산을 쉽게 수행가능

## 01  array
1차원 자료형

In [32]:
import numpy as np
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
type(a)

numpy.ndarray

In [33]:
# Slicing 에 용이하다 : list와 동일
a[:2]  

array([ 0. ,  0.5])

In [34]:
print(a.sum())     # 객체의 총합
print(a.std())     # 객체의 표준편차
print(a.cumsum())  # 객체의 누적합
print(a * 2)
np.sqrt(a)         # Sequare : 제곱근 (벡터화된 수학연산도 가능)

5.0
0.707106781187
[ 0.   0.5  1.5  3.   5. ]
[ 0.  1.  2.  3.  4.]


array([ 0.        ,  0.70710678,  1.        ,  1.22474487,  1.41421356])

## 02 array
2차원 자료형

In [35]:
b = np.array([a, a * 2])
print('b      :', b)
print('b[0]   :', b[0])      # 첫 행
print('b[0, 2]:',b[0, 2])   # 첫 행, 두번째 객체 
print('b.sum():',b.sum())

b      : [[ 0.   0.5  1.   1.5  2. ]
 [ 0.   1.   2.   3.   4. ]]
b[0]   : [ 0.   0.5  1.   1.5  2. ]
b[0, 2]: 1.0
b.sum(): 15.0


In [36]:
b.sum(axis=0)  # 0번 축의 합

array([ 0. ,  1.5,  3. ,  4.5,  6. ])

In [37]:
b.sum(axis=1)  # 1번 축의 합 (row/ column 의 구분이 아니다!!!!)

array([  5.,  10.])

## 03 ndarray
NOT-DEFINED-array : 특정한 원소값이 없이 생성을 시작한 객체

In [38]:
# also: np.ones()
c = np.zeros((2, 3, 4), dtype='i', order='C')  ; c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [39]:
# also: np.zeros_like()
d = np.ones_like(c, dtype='f16', order='C')  ; d

array([[[ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0]],

       [[ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0]]], dtype=float128)

In [ ]:
import random
I = 5000 

In [ ]:
%time mat = [[random.gauss(0, 1) for j in range(I)] for i in range(I)]
  # a nested list comprehension

In [ ]:
%time mat = np.random.standard_normal((I, I))

In [ ]:
%time mat.sum()

## 04 ndarray 의 구조화 배열 (Structured Arrays)
단일자료형 연산에 특화되어 있는 한계를 극복위해, 각 열마다 구조화 배열객체를 생성한다

In [ ]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'),
               ('Height', 'f'), ('Children/Pets', 'i4', 2)])
s = np.array([('Smith', 45, 1.83, (0, 1)),
              ('Jones', 53, 1.72, (2, 2))], dtype=dt)
s

In [ ]:
s['Name']

In [ ]:
s['Height'].mean()

In [ ]:
s[1]['Age']